### ISSUE TITLE
stock_analytic does not take analytic account from the orders

### ISSUE THREAD

**Issue by jalzaga** [OCA/account-analytic#137]
If my tests are correct in V10, the module is not really usable since you have to enter manually the analytic account in the stock picking. The analytic account is already set at the sale order header or at purchase order lines, when the pickings are created from those orders, the analytic account (and also the analytic tags) should be transferred to them.
It is not feasible to expect users to enter analytic accounts in all the generated stock pickings. Whatsmore, analytic accounts normally come from default analytic values.

**Comment by JordiBForgeFlow** [comment]
@jalzaga You are right. Module `stock_analytic` should depend on `procurement_analytic`, and pass in `_get_stock_move_values` the analytic account from the procurement from the stock.move.

So, in the end you @jalzaga will need `sale_procurement_analytic`, `stock_analytic` and `procurement_analytic` to be able to pass the analytic account from sales orders to stock moves.

@aheficent can you fix that?

**Comment by AaronHForgeFlow** [comment]
Solved.
