### ISSUE TITLE
analytic tag dimension - data is not saved in the custom fields

### ISSUE THREAD

**Issue by dominiquekonsuntack** [OCA/account-analytic#158]
Odoo 10 Community

How to reproduce
- Create dimension: e.g. District
- Create two tags: e.g North, South

In the database, the field "x_dimension_dis" is created - Accessible through pgadmin
create an invoice, and in the invoice line, select a tag e.g. "North"
Save the invoice
--> in the table account.invoice.line for that record, the field x_dimension_dis is still 'null'

Looking at the code, the line: 
    super(AnalyticDimensionLine, record).write(dimension_values)
is executed, but .. the data is not written in the DB.

No clue..

**Comment by fclementic2c** [comment]
I confirm the issue. 

Wondering if it does not come from: https://github.com/OCA/account-analytic/commit/d9fa797c2da31b4197a6e6421a31f3004cd190e1#diff-fd29d4a60e14f0cd6bc10de811b01ee8

However, if you remove this commit then the bug on pivot table on analytic lines will be back :\ 

cc: @mpanarin

**Comment by santiago1976** [comment]
Any update on this issue?

I confirm it doesn't work in Odoo 10 Community

I config a new dimension and assign a new label.

Then, I create a new invoice and assign this new label, but when I try to group by this dimension in analytic entries, it doesn't work

Thanks

**Comment by pedrobaeza** [comment]
Is this still happening? At least in upper versions is not happening.
