### ISSUE TITLE
Account Analytic Required or is buggy or the documentation is lacking 

### ISSUE THREAD

**Issue by icf20** [OCA/account-analytic#174]
![image](https://user-images.githubusercontent.com/17784575/40548075-f6ca09a8-6033-11e8-8e02-4809b30197e3.png)

http://3326545-11-0-c40d8e.runbot1.odoo-community.org/web?debug=1#id=5&view_type=form&model=account.invoice&menu_id=239&action=329

does anyone **care** to explain how this should work ?

**Comment by pedrobaeza** [comment]
If you analyze the message, it's saying the payable account (11100) doesn't have analytic account, and that's true, as that one is never going to have an analytic account. Expenses and income accounts are the one that get the analytic accounts.

**Comment by icf20** [comment]
@pedrobaeza this why is the option enabled on those ?

**Comment by pedrobaeza** [comment]
I don't know, but as said, it's not a bug.
