### ISSUE TITLE
[10.0] purchase_procurement_analytic: No grouping

### ISSUE THREAD

**Issue by rousseldenis** [OCA/account-analytic#175]
@cubells The module purchase_procurement_analytic does not group purchase orders by analytic. Tested on runbot.

I think that's because the search method is implemented on purchase order lines and not purchase order model.

Moreover it's better not to use the context but use the '_make_po_get_domain' method in procurement.

And for a conclusion, I think the grouping should be an option as sometimes you don't want to separate purchase orders simply on analytic account (but keeping the analytic transmission through procurements and moves).

I've added some comments on https://github.com/OCA/purchase-workflow/pull/392 also linked to this module.

**Comment by rousseldenis** [comment]
See https://github.com/OCA/account-analytic/pull/176/

**Comment by pedrobaeza** [comment]
Closing as there's a PR.

**Comment by cubells** [comment]
You are right @rousseldenis 
thanks!
