### ISSUE TITLE
[10.0] (purchase_procurement_analytic) Isn't grouping the lines of products with different analytic account on same purchase order for the same supplier

### ISSUE THREAD

**Issue by vinclar** [OCA/account-analytic#185]
**Use of case:**
You have five orders with different analytic account from different customers, two different products (A and B) from the same supplier A. Same route applies in this case Make to order

SO 1 from customer A, Analytic_account A - Orders 1 u. Product A and 1 u. Product B
SO 2 from customer B, Analytic_account B  - Orders 3 u. Product A
SO 3 from customer C, with no analytic  - Orders 5 u. Product B
SO 4 from customer D, with no analytic  - Orders 5 u. Product A
SO 5 from customer E, Analytic_account B - Orders 5 u. Product A

**Expected behaviour:**
One purchase order to supplier A with the following lines:
1 u. Product A with Analytic_account A
8 u. Product A with Analytic_account B
1 u. Product B with Analytic_account A
5 u. Product B with no analytic
5 u. Product A with no analytic

**Effective result:**
3 different orders, one for each analytic account and one
PO 1: Equals to SO 1
PO 2: Equals to SO 2 + SO 5 correctly merged in one line as it is same product and analytic
PO 3: Equals to SO 3 + SO 4 correctly not merged in one line as it isn't same product

The grouping on the same purchase order is limited to the same analytic account or none, that limitation should be on the lines not on the document itself.
Is this behaviour intended?

If you need clarification I will be more than pleased to do it. # @rousseldenis @cubells

**Comment by pedrobaeza** [comment]
I think #179 solves this issue

**Comment by vinclar** [comment]
Thanks, I just test it. 
No changes with the patch, the result still is the same, different purchase quotations for every analytic account.
The commit, what I understood that it does is to solve "If purchase orders were generated through bare procurement orders, generated moves do not contain the analytic account set on procurement." and this case is procurements generated from a sales order. The default behaviour(without analytic) is grouping the lines into the same purchase order to the same supplier.

**Comment by cubells** [comment]
@vinclar I'll review later your information. Thanks.
