### ISSUE TITLE
[10.0]account_analytic_parent. Debit, credit and balance computation is super slow.

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/account-analytic#198]
When overriding the method that computes those fields here: https://github.com/OCA/account-analytic/blob/10.0/account_analytic_parent/models/account_analytic_account.py#L24 Odoo calls the same method for all the children and it gets extremely slow when the number of analytic accounts grow, specially with many children.

We can make those fields stored but then we have to make sure it is recomputed everytime its needed and it's complex.

Any ideas are welcome! :hugs:

**Comment by pedrobaeza** [comment]
Use `read_group` for computing them. Your colleague @mreficent made something similar in contracts.

**Comment by AaronHForgeFlow** [comment]
Ok thanks, @mreficent can you point me to that change? I could not find it in contracts.

**Comment by MiquelRForgeFlow** [comment]
https://github.com/OCA/contract/pull/170/commits/402370f1cbe5cde6b484200f87596e9d803a36af#diff-3dc0d52ea9449a93459ef5b7fc36a060R19

**Comment by AaronHForgeFlow** [comment]
Thanks @mreficent

**Comment by AaronHForgeFlow** [comment]
Cannot group_by non stored fields. And read group does not return the values that are not in the group_by. I'll go for a query instead.

edit:I can read_group the analytic lines but that would be duplicating the core method

**Comment by pedrobaeza** [comment]
@aheficent this has nothing to do with stored/non stored. Please use `read_group` properly.

**Comment by AaronHForgeFlow** [comment]
Do you mean to read_group in the analytic lines and not call super instead?
update: I think I got it...

**Comment by pedrobaeza** [comment]
Well, you limit the read_group in the domain to the `self.ids` scope.
