### ISSUE TITLE
Manufacturing order does not take analytic account from the Sales orders

### ISSUE THREAD

**Issue by HannaRoosta** [OCA/account-analytic#214]
First of all I want to thank you for very useful App, but i have an issue that needs your help to solve it.
After setting analytic account in our Sales Orders when Manufacturing Order created based on the related SO, analytic account not shown in MO. It means you must check the MO one by one and add analytic account manually which takes time and it's very complex as lots of SO is created everyday.

Any ideas are welcome :)

**Comment by pedrobaeza** [comment]
Which module? Which version?

**Comment by HannaRoosta** [comment]
> Which module? Which version?

Dear Pedro

We use analytic for manufacturing module (mrp_analytic) for odoo enterprise version 11.

**Comment by pedrobaeza** [comment]
And the module from this repo that you are using?

**Comment by HannaRoosta** [comment]
> And the module from this repo that you are using?

Sorry i didn't understand what you mean, would you please explain more?

**Comment by pedrobaeza** [comment]
Then you are confusing what is this repo. This a repository outside Odoo for hosting modules referring to analytic accounting. If your issue is with Odoo itself, and having enteprise contract, then please put a ticket in odoo.com/help.
