### ISSUE TITLE
12.0 Why not store parent on analytic parent module 

### ISSUE THREAD

**Issue by ovnicraft** [OCA/account-analytic#224]
`account_analytic_parent` module was migrated to 12.0 so, odoo introduce a new algorithm to compute `_parent_store` https://github.com/odoo/odoo/blob/12.0/odoo/models.py#L2261

Could improve performance on analytics set `_parent_store = True` ?

**Comment by ovnicraft** [comment]
@moylop260 WDYT about this?

**Comment by pedrobaeza** [comment]
This is being done in #225
