### ISSUE TITLE
[12.0][ADD] stock_request_analytic

### ISSUE THREAD

**Issue by max3903** [OCA/account-analytic#248]
This module allows you to set an analytic account on requests and request orders and push it to the generated transfers and moves.

# Technical Specifications

# Dependencies

- [ ] stock_analytic: https://github.com/OCA/account-analytic/issues/247

# stock.request

- [ ] Add a many2one field "Analytic Account" (analytic_account_id)
- [ ] Extend _prepare_procurement_values() to pass the analytic_account_id field

# stock.request.order

- [ ] Add a many2one field "Analytic Account" (analytic_account_id)
- [ ] Extend create(): if the analytic account is set, update all the related stock requests with the same analytic account
- [ ] Extend write(): if the analytic account is updated, update all the related stock requests with the same analytic account

**Comment by AaronHForgeFlow** [comment]
Hi @max3903, this module is already available in v11 and v12 but in another repo:
https://github.com/OCA/stock-logistics-warehouse/tree/12.0/stock_request_analytic

**Comment by max3903** [comment]
@aheficent Thank you. Does it push the analytic account to the transfers and stock moves?

**Comment by AaronHForgeFlow** [comment]
@max3903 yes :)

**Comment by max3903** [comment]
@aheficent Awesome. Thank you!. Have a great week.

**Comment by AaronHForgeFlow** [comment]
Welcome! Have a great week you too.
