### ISSUE TITLE
[12.0] stock_analytic: analytic_account_id field is read only!

### ISSUE THREAD

**Issue by Jerther** [OCA/account-analytic#257]
I went to a Odoo runbot for 12.0 and tried to do just as the README file says and the field is readonly: 

![](https://i.imgur.com/AL9HkPl.gif)

**Comment by AaronHForgeFlow** [comment]
The analytic account is editable on the stock.move (Operations tab), but not the stock.move.line (Detailed operations).

The analytic account is not readonly in the stock move. However, the field is not visible in the tree view inside the picking. I would accept that change if someone proposes a pull request.

**Comment by Jerther** [comment]
I'll do just that then :wink:
