### ISSUE TITLE
8.0  account_analytic_required  depends

### ISSUE THREAD

**Issue by bjoliveau** [OCA/account-analytic#27]
Maybe this module have to contain a depend with account_accountant  and analytic.

I installed them and didn't get the new features in analytic account for typing it with  policies : always, never and optional.

Is it ready and tested for v8, maybe i missed a parameter...

**Comment by sbidoul** [comment]
Hi,

The module works fine on 8.0. Note the the configuration field appears on Account Type, not Analytic Account.

-sbi
