### ISSUE TITLE
[11.0/12.0] Stock analytic 

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/account-analytic#284]
Hi all,

I think this commit:
https://github.com/odoo/odoo/commit/24c7efc8fef63437ac28883b29ed84809234ed76

Will break functionality of the module stock analytic?

Since the booking for the stock_account_output from the customer invoice will not contain an analytic account, the analytic account will never be balanced?

@max3903 @AaronHForgeFlow

**Comment by AaronHForgeFlow** [comment]
I am afraid we will have to override this method in stock_analytic module :disappointed:

**Comment by AaronHForgeFlow** [comment]
The original PR in Odoo https://github.com/odoo/odoo/pull/43654

**Comment by CasVissers-360ERP** [comment]
I'm trying to get old functionality back, see odoo/odoo@24c7efc. 

If they don't agree I think the only possibility is to override the method.

**Comment by CasVissers-360ERP** [comment]
@AaronHForgeFlow 
Shall I apply the fix suggested by @nim-odoo in odoo/odoo@24c7efc?

**Comment by AaronHForgeFlow** [comment]
Yes, I think so. They did not revert the changes but at least they did the coding for us :)

```
@api.model
def _anglo_saxon_sale_move_lines(self, name, product, uom, qty, price_unit, currency=False, amount_currency=False, fiscal_position=False, account_analytic=False, analytic_tags=False):
    res = super()._anglo_saxon_sale_move_lines(
        name,
        product,
        uom,
        qty,
        price_unit,
        currency=currency,
        amount_currency=amount_currency,
        fiscal_position=fiscal_position,
        account_analytic=account_analytic,
        analytic_tags=analytic_tags,
    )
    if res:
        res[0]['account_analytic_id'] = account_analytic and account_analytic.id
        res[0]['analytic_tag_ids'] = analytic_tags and analytic_tags.ids and [(6, 0, analytic_tags.ids)] or False
    return res
```

**Comment by CasVissers-360ERP** [comment]
@AaronHForgeFlow 
Can you check #286? If ok I will make a PR for v11 as well.
