### ISSUE TITLE
Mrp analytic

### ISSUE THREAD

**Issue by gjlong68** [OCA/account-analytic#346]
Add move lines and fill analytic account and analytic tags fields

**Comment by pedrobaeza** [comment]
What do you mean?

**Comment by gjlong68** [comment]
mrp analytic improve,see the attachment for further information




&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; goodluck




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OCA/account-analytic"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 下午3:12
收件人:&nbsp;"OCA/account-analytic"<account-analytic@noreply.github.com&gt;;
抄送:&nbsp;"郭Sir"<gjlong008@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [OCA/account-analytic] Mrp analytic (#346)





 
What do you mean?

**Comment by pedrobaeza** [comment]
There's no attachment, but this is for issues or blueprints, or at least explained wishlist, not only 2 sentences.

**Comment by gjlong68** [comment]
Add analytic account to a production-related entry:
 
1、OCA App Install: 
 


 
2、Create Manufacture Order (Analytic Account)：
 


 
Valuation
 


 


 
3、Account Move： Take analytic account to the account move line
 


 
&nbsp;

     
                

主题:&nbsp;Re: [OCA/account-analytic] Mrp analytic (#346)





 
There's no attachment, but this is for issues or blueprints, or at least explained wishlist, not only 2 sentences.

**Comment by pedrobaeza** [comment]
There are no images the way you are sending your replies.
