### ISSUE TITLE
Travis is red because odoo recent change

### ISSUE THREAD

**Issue by antespi** [OCA/account-analytic#38]
Current 8.0 error: https://travis-ci.org/OCA/account-analytic/jobs/77282014#L218
Seems to be related with analytic_multicurrency.

@yvaucher, @guewen could you review this? Thanks

**Comment by yvaucher** [comment]
@antespi @guewen It seems travis job has been restarted and everything is green. (or am I missing something ?)
Thus I'll close this. We will reopen it with more details if it happens again.

**Comment by antespi** [comment]
All green. Thanks @yvaucher
