### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by herfjord** [OCA/account-analytic#401]
module: stock_analytic
version: 14.0

**Steps to reproduce**
- ...

**Current behavior**
The module is adding the analytic fields to stock moves as anticipated, and track the cost moves correctly

**Expected behavior**
It would be extremely handy if the fields were auto-populated when the stock move is generated by a sales order with an analytic account set upon confirmation

**Comment by etoimene** [comment]
Have you tried sale_stock_analytic?

**Comment by herfjord** [comment]
Thanks! I'll look into it :)
