### ISSUE TITLE
 _io.BufferedReader' object has no attribute 'decode'

### ISSUE THREAD

**Issue by E4O** [OCA/account-analytic#445]
When I try to add a submodule account-analytic or stock-logistics-workflow to Odoo.sh Settings, I will get an error:
 _io.BufferedReader' object has no attribute 'decode'

1. Add Submodule git@github.com:OCA/account-analytic.git to Odoo.sh (v14).
2. Run submodule on staging.

There shouldn't be errors during this. Odoo referred to this solution:
https://programmerclick-com.translate.goog/article/8006810430/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=fr&_x_tr_pto=wapp

**Comment by E4O** [comment]
Still no feedback!

**Comment by pedrobaeza** [comment]
This has nothing to do with the module itself, it's your deployment technique, so closing. Please ask in forums.
