### ISSUE TITLE
Blueprint: Multi Dimension Analytic Accounts

### ISSUE THREAD

**Issue by dreispt** [OCA/account-analytic#54]
Add multidimension analytic accounting to Odoo, by leveraging the already Analytic Account existing features. 
Full description: https://gist.github.com/dreispt/d4eccdf998f1d6c9221c

**Comment by rafaelbn** [comment]
Hi @dreispt , is there any work on this for OCA in this moment? Thanks!
cc @pedrobaeza

**Comment by dreispt** [comment]
Hi, I'm pretty sure I won't be able to do any work on this in the foreseeable future.
Be my guest to take over it.
