### ISSUE TITLE
How the OCA will deal with the disappearance of analytic tags

### ISSUE THREAD

**Issue by rafaelbn** [OCA/account-analytic#551]
Hello all,

Odoo deletes and loses all analytics tags in Odoo 16

OCA has lot of modules over this model

1. account.analytic.group-> account.analytic.plan
2. account.analytic.account -> account.analytic.account
3. account.analytic.tag -> Deletes (All data is lost)
4. account.analytic.default` -> Deletes (All data is lost)

I would like to discuss what is on @OCA/accounting-maintainers and general with contributors what should be done in:

- [ ] Module migrations
- [ ] OpenUpgrade

### Analytic Tags should be maintained just as tags

**Analytic tags had 2 functions:**

- For labeling analtytic lines + account moves
- Making analytical distributions

i.e. it does 2 things

**Analytic plans have 1 function:**

- Multiple distributions in different plans

IMHO: The new analytical plans are the new distributions, but the **analytical tags must be maintained by removing the distribution function**.

Thank you
Regards

**Comment by kharkot** [comment]
Hello ,

In that subject I have logged ticket to Odoo - you can track my correspondence https://www.odoo.com/my/tasks/3173120?access_token=f9c64ccd-b1a9-4e36-905c-29a082c14426  

For while functionality (only field on account.move) was removed but....

**Comment by rafaelbn** [comment]
### Analytic Tags should be maintained just as tags

**Analytic tags had 2 functions**

- For labeling analtytic lines + account moves
- Making analytical distributions

i.e. it does 2 things

**Analytic plans have 1 function:**

- Multiple distributions in different plans

IMHO: The new analytical plans are the new distributions, but the **analytical tags must be maintained by removing the distribution function**.

**Comment by kharkot** [comment]
@rafaelbn 
Recommendation from Odoo:

`Since you are in Odoo 15, I would recommend you to not upgrade to Odoo 16 and wait for Odoo 17 which will have its analytic tags way of working improved.

Once again, we apologize that the changes made in Odoo 16 do not suit you and your business.
We are already working on it to improve it in Odoo 17.`

**Comment by Shide** [comment]
I've found a problem when migration has been done via Odoo.
The relation with `account.move.line` and `account.analytic.tag` has been stored on the table `account_analytic_tag_account_move_line_rel`.

When Odoo is migrating, removes the table from the database, and it causes losing all the data.
It's important to keep in mind this issue before migrating with Odoo. Be sure to maintain a copy of the old database in order to script something when Odoo (or OCA) decides to resolve the Analytic Tag problem.

MT-2742

**Comment by alan196** [comment]
I'm with @rafaelbn 

The analytic tags must be maintained, removing the distribution function.

**Comment by OSevangelist** [comment]
@rafaelbn @alan196 @Shide @kharkot @rvalyi @sbidoul has any of you seen any PR on the current SaaS branches that seem to indicate the strategy of further development at Odoo S.A. with regard to https://github.com/OCA/account-analytic/issues/551#issuecomment-1491702607

**Comment by kharkot** [comment]
@OSevangelist "strategy of further development at Odoo S.A. " does really such strategy exist? 

My knowledge comes only from https://www.odoo.com/my/tasks/3173120?access_token=f9c64ccd-b1a9-4e36-905c-29a082c14426

_"...the Product Owner is aware of the current situation with analytic tags in Odoo 16 and will take the necessary actions to provide you with a similar workflow and the same capabilities in Odoo 17."_

**Comment by Saran440** [comment]
@rafaelbn

I think that analytic tags are important data for viewing reports from various perspectives.
Therefore, we should create a new analytic tags module for tags only.

**Comment by rafaelbn** [comment]
Mainly we all agree, there is a topic for OCA Days in Valencia. I wish we would have time for it.

**Comment by william-andre** [comment]
Hello!

Just to keep you updated, we (Odoo) are working on migrating both `account.analytic.tag` and `account.analytic.default` in the official upgrade code.

**Comment by legalsylvain** [comment]
Thanks @william-andre for the notification ! 

could you specify for which version this change will be made? 16 ? saas-16.x ? 17 ? 
thank you !

**Comment by william-andre** [comment]
It is not merged yet, but it should be working for all migrations from 15.0 to 16.0.
It won't be retroactive though, there is no way to repair databases migrated before that is merged.

**Comment by rafaelbn** [comment]
Thank you very much @william-andre !

> Just to keep you updated, we (Odoo) are working on migrating both account.analytic.tag and account.analytic.default in the official upgrade code.

It would be great if you ping us when done or in PR

Best!

**Comment by william-andre** [comment]
One of the two pull requests just got merged (regarding the tags):
https://github.com/odoo/upgrade/commit/5a516fc9d2964109f4f33285b2dab8681b8be67f (if you have access...)
I am not sure when it will be taken into account for new upgrade requests, but it should be used around next week (maybe now already)

The PR for the defaults is still in review.

**Comment by legalsylvain** [comment]
@william-andre. Just to be sure. there is no change in the model. You just fixed your migration script, right ?

**Comment by william-andre** [comment]
Yes, only the upgrade script changed.
The tags are upgraded as accounts in a specific group of account created during the migration to keep them separate from other analytic accounts.

**Comment by rafaelbn** [comment]
> The tags are upgraded as accounts in a specific group of account created during the migration to keep them separate from other analytic accounts.

Mainly then, that analytic dimension (tags) are then lost to we will have to recover it in OCA

I agree @Saran440 

> I think that analytic tags are important data for viewing reports from various perspectives.
Therefore, we should create a new analytic tags module for tags only.

We will think about this in Spanish OCA Days 2023 in Valencia: https://docs.google.com/document/d/13qGJMKDbxiM76g7_jpGLEs0lPD39QZ5eCT4t3ln-tYA/edit#bookmark=id.lrnzynbp8ibe

**Comment by william-andre** [comment]
> Mainly then, that analytic dimension (tags) are then lost to we will have to recover it in OCA

The analytic plans keep the same dimension as what the tags used to have

**Comment by kharkot** [comment]
@william-andre 
So there will be no account.analytic.tag  as m2m relation to account.move.line? 
Instead that migration scripts will create analytic plans? 

Jérôme Gérard (in https://www.odoo.com/my/tasks/3173120?access_token=f9c64ccd-b1a9-4e36-905c-29a082c14426) wrote "Since you are in Odoo 15, I would recommend you to not upgrade to Odoo 16 and wait for Odoo 17 which will have its analytic tags way of working improved." - that suggest that account.analytic.tag will be restored in R17.

I do not understand whole situation - please clarify it so I could inform our customers what to do.

**Comment by rafaelbn** [comment]
Hello @william-andre ,

Thank you very much for participating 😄 

Odoo SA in my opinion get a big mistake because Analytic Plans are Account Groups so you as the solution is convert Analytic Tags to Analytic Groups we are missing the same, the problem.

> The analytic plans keep the same dimension as what the tags used to have

This is not a financial solutions. This is a lost of financial dimensions because:

1. Analytic plans are related to analytic account
2. Analytic tags where independent + multi value. Independent. Same Analytic Account can have different Analytics tags and now Odoo pretend to create 1 `account.analytic.line` per analytic plan? Because if you want 100% amount of an analytic account in different plans you have to inform it and therefore more time and cost and duplicated info.
3. You cannot analyse therefore analytic account (for example project) that is indivisible across multiple analytic plans 

| Project | Analytic | Tag 1  | Tag 2         | Tag 3 |
| ---     | ---      | ---    | ---           | ---   |
| WO-111  | WO-111   | Naval  | National      | replacement |
| WO-112  | WO-112   | Naval  | International | service |
| WO-113  | WO-113   | Air    | National      | service |
| WO-114  | WO-114   | Ground | International | service |
| WO-115  | WO-115   | Naval  | National      | replacement |
| WO-116  | WO-116   | Air    | International | replacement |
| WO-117  | WO-117   | Ground | National      | replacement |

Note: each is only 1 `account.analytic.line`

All the Project and Analytic is created from Sales Orders and every day 50 new SO.
No body needs to inform anything in invoices because Analytic is created in each SO and Tags are informed in the Sale Order.

I can imagine there a really many use cases and that is why Analytic Tags where a second independent dimension

Sadly, the new functionality was thought (IMHO) for a really few cases and always to inform from Invoices. A really short point of view in an ERP.

I have think and work around this about 7 months and still thinking because after working 5 months in Odoo 16 I still not catch the Odoo SA approach. Product Owner should Bird's-eye view to get more perspective and think about more use cases that exist since OpenERP 5.

I love dialogue and learning! Thank you! ❤️

**Comment by daiduongnguyen-odoo** [comment]
> 

I don't understand your mean as i am struggling in migrating both `analytic` and `account` , could you explain a little bit please ? i would be grateful

**Comment by rafaelbn** [comment]
Hello all,

As more I review as more I think that really Odoo didn't think this and miss this use case. I've recorded a video and prepated and Excel. The use case I explaiin was possible from OpenERP to Odoo 15 😄 

[Use case example Odoo analytic tags.xlsx](https://github.com/OCA/account-analytic/files/12307347/Use.case.example.Odoo.analytic.tags.xlsx)


https://github.com/OCA/account-analytic/assets/8736623/7be08db7-9731-4366-806c-044865fc0db3

I wish this helps

Regards,
Rafael

Ping @omar7r @nhomar @angelmoya @moylop260

**Comment by sbidoul** [comment]
We are considering to contribute an `account_analytic_tag` module that reintroduces the `account.analytic.tag` model (with only the `name`, `color`, `active` and `company` fields). This module would just provide the model and the tree view to configure analytic tags (no other logic nor relations to other models).

Would that be useful to anyone?

**Comment by rafaelbn** [comment]
This issue is solved mainly in https://github.com/OCA/account-analytic/pull/572 so closing! 😄 🪂
