### ISSUE TITLE
Feature request / user configuration

### ISSUE THREAD

**Issue by herfjord** [OCA/account-analytic#557]
module: stock_analytic
version: 16.0

Dear, valued, OCA,

We are using Stock Analytic to track cost for items taken from our inventory into our projects. It's a riddle to me, why this isn't featured in Odoo natively.

However,
Is there any way to auto-populate the analytic field in the delivery order in the inventory app with the analytic account selected in the sales order?
![Screenshot 2023-05-19 14 04 18](https://github.com/OCA/account-analytic/assets/39625047/18b8959e-dbd8-45b1-9f73-2bfddaab7674)

As of now, we need to add the correct analytic order to each and every line in the delivery order.

All the best,
Henning

**Comment by yostashiro** [comment]
@herfjord I guess this is what you are looking for: https://github.com/OCA/account-analytic/pull/511

**Comment by herfjord** [comment]
@yostashiro - Thanks a lot for your reply :)
However, the column for Analytics is not populated still. Meaning I have to manually enter the analytic account on each of the delivery orders product lines.
Should it / Could it be automatically populated based on the sales order? (tested on runboat)
![Screenshot 2023-05-19 15 30 59](https://github.com/OCA/account-analytic/assets/39625047/ea28ef7b-3f51-409c-b03c-8f632a4dc1f1)

**Comment by yostashiro** [comment]
@herfjord I think the PR needs to be rebased. I suggest you test it locally in the mean time.
