### ISSUE TITLE
stock_analytics module not passing the  analytical account in the product's valuation account 

### ISSUE THREAD

**Issue by kkumawat25** [OCA/account-analytic#562]
" Journal item with account equal to product's valuation account will not be assigned to any analytic account" Any reason of not passing analytical account in product's valuation account in stock_analytics module ?
@mymage @francesco-ooops

**Comment by mymage** [comment]
Hi @kkumawat25, Francesco and I have only done the translation for Italian language.
I think the question should have been directed to the authors/contributors.
