### ISSUE TITLE
Autocomplete analytical account in delivery orders, inventory module, odoo 16 community

### ISSUE THREAD

**Issue by porrasadrian** [OCA/account-analytic#575]
It is possible that the analytical field is auto-completed when selecting a specific product (try to apply the same logic as the analytical distribution section but now in inventory),
Despite configuring a distribution model, it only applies to invoices and sales, but not to inventory, and the option of applicability to stock movements does not appear in the analytical plans
![1](https://github.com/OCA/account-analytic/assets/57052161/bb720a5e-d039-42fc-823d-417276256099)
![2](https://github.com/OCA/account-analytic/assets/57052161/b0682643-351d-4e51-8546-dc2306b82f3e)

**Comment by pedrobaeza** [comment]
This is a doubt about functional aspects of Odoo core, not an issue with one of the modules of this repository, so please ask it in the forums.

Closing as not related.
