### ISSUE TITLE
[16.0] purchase_analytic: Throws error when users don't belong to Technical/Analytic Accounting

### ISSUE THREAD

**Issue by kikopeiro** [OCA/account-analytic#591]
## Module
purchase_analytic

## Describe the bug
Throws error when users don't belong to Technical/Analytic Accounting

Seems related with this PR -> https://github.com/OCA/account-analytic/pull/561

## To Reproduce
**Affected versions**:

1. With user that don't belong to Technical/Analytic Accounting
2. Try to access Purchase > Orders > Requests for Quotation > Any record
3. Next error is throwed

![Selección_1125](https://github.com/OCA/account-analytic/assets/4610000/df9a628a-7afb-4ef4-b98c-f1f54fbd4372)

CC @yostashiro @AungKoKoLin1997 @AaronHForgeFlow

**Comment by yostashiro** [comment]
Thanks for the report. We should do the same as https://github.com/OCA/account-analytic/blob/879922211cf8f82cdb4b729649b478f52a3f4758/stock_picking_analytic/views/stock_picking.xml#L12-L17 for the `analytic_distribution` field in the view.

@AungKoKoLin1997 Can you please follow up with a PR to fix this.

**Comment by AungKoKoLin1997** [comment]
I created a PR to fix this.
https://github.com/OCA/account-analytic/pull/592

**Comment by kikopeiro** [comment]
Thanks @yostashiro @AungKoKoLin1997 ! Good job!
