### ISSUE TITLE
account-analytic-16.0-stock_analytic  seems locked

### ISSUE THREAD

**Issue by Jan-Onestein** [OCA/account-analytic#597]
Hello,

module account-analytic-16.0-stock_analytic  seeps to be locked for translation ??

Can anyone please double check  and if possible release it ??
We want to do some Dutch translations.

Dutch greetings,
Jan

**Comment by Jan-Onestein** [comment]
*bump*
Can someone please have a look at the translation lock ??
@pedrobaeza can you do anything about the locking ??

Thanks in advance !!!

**Comment by pedrobaeza** [comment]
Unlocked. Not sure why this is still happening...
