### ISSUE TITLE
[9.0] blueprint: account_analytic_parent

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-analytic#65]
The analytic accounts hierarchy has been removed in v9.

Whereas for G/L accounts, the notion of hierarchy is debatable and I think it was a good thing to remove it, I believe such a concept is useful for analytic accounts.

We would therefore start with a first module named `account_analytic_parent` that reintroduces `parent_id` and `child_ids` on `account.analytic.account`, together with the parent_left/parent_right mechanism for performance. 

This module would be a foundation for other modules wishing to build on the hierarchy concept.

Is there an interest to have this in OCA?

**Comment by pedrobaeza** [comment]
I have the exact feeling, because the concept is more natural than tags. :+1: for creating it.

**Comment by fclementic2c** [comment]
+1 

(Actually, I am in va favour of totally forking analytic accounting in Odoo)

**Comment by elicoidal** [comment]
:+1:
(it will probably have to go with project parenting)

**Comment by sbidoul** [comment]
> (Actually, I am in va favour of totally forking analytic accounting in Odoo)

@fclementic2c me too... but that's another story.

**Comment by pedrobaeza** [comment]
@sbidoul, have you worked something in this topic?

**Comment by sbidoul** [comment]
@pedrobaeza no, the use case went away for the moment.

**Comment by pedrobaeza** [comment]
OK, thanks for saying.

**Comment by levkar** [comment]
Analytic distribution is also removed.  Would it be possible to implement it with a new 'distribution' type and child analytics?

Lack of this feature also disables Project hierarchy, doesn't it?

**Comment by pedrobaeza** [comment]
Yeah, that features are also desirable, but that means more work...

**Comment by JordiBForgeFlow** [comment]
We are going to work on this topic (analytic parent, not analytic distribution). @aheficent will be working on it.

**Comment by stellaf** [comment]
analytic parent, would be great. Thanks.

**Comment by pedrobaeza** [comment]
The base module is now merged, but I see one problem: there's no tree view that uses this information. @jbeficent, don't you think that base module should include the same tree view as it was in v8?

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza I think you're right. I'll create a new PR with the changes in the view.

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza is it really needed to add the field parent_id in the tree view? In odoo8 the field is added but is invisible:
![image](https://cloud.githubusercontent.com/assets/19620251/25388483/4e8ce41e-29ce-11e7-9767-f801aa914cec.png)

**Comment by pedrobaeza** [comment]
I'm not talking of that, but the tree view in tree mode:

![imagen](https://cloud.githubusercontent.com/assets/7165771/25451349/24578eb6-2ac2-11e7-82ac-9ff451d9f02b.png)

**Comment by dreispt** [comment]
@jbeficent this could be a good opportunity to factor in WBS support.

**Comment by AaronHForgeFlow** [comment]
I agree @dreispt We're working on that also

**Comment by pedrobaeza** [comment]
As the module is merged and the functionality restored, I think we can close this. If new features appear, they can be discussed in other issues/PRs.

**Comment by cubells** [comment]
@aheficent @jbeficent 

Thanks for adding that hierarchical view tot analytic accounts.

It would be possible to open the same view when you click on Accounting>Adviser>Analytic accounts and open charts?

I think that by doing it's collected better data for accounting advisers.

**Comment by pedrobaeza** [comment]
I agree, because on that view you have the possibility to pre-filter by dates and then having hierarchical totals. It was that way on v8.
