### ISSUE TITLE
[10.0] analytic_tag_dimension causes WARNING log lines and "red" runbot build

### ISSUE THREAD

**Issue by gurneyalex** [OCA/account-analytic#96]
```
2017-05-05 22:13:12,729 174 INFO openerp_test odoo.modules.registry: module analytic_tag_dimension: creating or updating database tables
2017-05-05 22:13:12,867 174 INFO openerp_test odoo.sql_db: bad query: ALTER TABLE "account_analytic_tag" ALTER COLUMN "analytic_dimension_id" SET NOT NULL
2017-05-05 22:13:12,868 174 WARNING openerp_test odoo.models: WARNING: unable to set column analytic_dimension_id of table account_analytic_tag not null !
Try to re-run: openerp-server --update=module
If it doesn't work, update records and execute manually:
ALTER TABLE account_analytic_tag ALTER COLUMN analytic_dimension_id SET NOT NULL
Traceback (most recent call last):
File "/.repo_requirements/odoo/odoo/models.py", line 2531, in _auto_init
cr.execute('ALTER TABLE "%s" ALTER COLUMN "%s" SET NOT NULL' % (self._table, name))
File "/.repo_requirements/odoo/odoo/sql_db.py", line 141, in wrapper
return f(self, *args, **kwargs)
File "/.repo_requirements/odoo/odoo/sql_db.py", line 218, in execute
res = self._obj.execute(query, params)
IntegrityError: column "analytic_dimension_id" contains null values
```

**Comment by gurneyalex** [comment]
@angelmoya could you look into this?

**Comment by angelmoya** [comment]
OK, field analytic_dimension_id on table account_analytic_tag.

When you install this module, and you have previous analytic tags, this analytic tags has no analytic dimension.

How can we proceed with this?

- Do it not required field
- Create default dimension
- ...

Maybe do it not required could be better

**Comment by pedrobaeza** [comment]
Other option is to add demo data for existing records that adds these dimensions, but maybe it's better to have the required only in views, not in data. It depends on the reason why you want to have this as required.

**Comment by gurneyalex** [comment]
the short path is to have the required column added to the demo data of the depending modules. 

another possibility is to rework the addon to allow tags to *not* specify a dimension, but this is more work in the addon in my opinion. I'm not sure which way you want to go.

**Comment by hbrunn** [comment]
what I often do just to satisfy tests is
```python
from openerp import tools
myfield = fields.Many2one(default=lambda self:
        tools.config['test_enable'] and self.env['model'].sudo().create({})
        or self.env['model']
```

**Comment by Cedric-Pigeon** [comment]
@angelmoya Do you plan to do something ? Several PR are red and blocked because of this. Thanks

**Comment by angelmoya** [comment]
Sorry Cedric-Pigeon, I had been to busy this week, I will try to do it today

**Comment by angelmoya** [comment]
#98
